#!/bin/sh
OBJDUMP=arm-none-eabi-objdump
if [ x$1 == "x" ]; then
	echo "$0 <Sourcefile>"
else
	sourcefile=`basename -s .o $1`
	#$OBJDUMP -rdj .text -j .data -j .bss $sourcefile.o > $sourcefile.objdump
	$OBJDUMP -D $sourcefile.o > $sourcefile.objdump
fi

