#!/bin/sh
GCC=arm-none-eabi-gcc
#VERBOSE=-fverbose-asm
if [ x$1 == "x" ]; then
	echo "$0 <Sourcefile>"
else
	sourcefile=`basename -s .S $1`
	$GCC -D__ASSEMBLY__ -x assembler-with-cpp -g -mcpu=arm7tdmi -c -Os $VERBOSE -Wall -I. -Wa,-a=$sourcefile.lst -o $sourcefile.o $sourcefile.S
fi
