#!/bin/sh
# If using Apple's python, use the following to enable 32-bit python
# arch -i386 does not work reliably except with specific python versions
# python2.6 and python2.7 is known to work with 'arch -i386'
#
# Apple recommends the use of the following Environment Variable to control
# 32-bit vs. 64-bit python selection
# export VERSIONER_PYTHON_PREFER_32_BIT="yes"

DARWIN=`uname`
DARWINVER=`uname -r |cut -f 1 -d .`
PYTHON=python
PYTHONVER=`$PYTHON --version`

# Mountain Lion (10.8) and Mavericks (10.9) hack support using 10.7 IOBluetooth framework
#IOBLUETOOTH_DIR=$( cd "$( dirname "$0" )" && pwd )
IOBLUETOOTH_DIR=$HOME/Library
DYLDPATH="DYLD_INSERT_LIBRARIES=$IOBLUETOOTH_DIR/IOBluetooth-Compat.dylib"

GDBSERVER=../nxos/armdebug/Host/nxt-gdb-server.py
if [ $DARWIN == "Darwin" ]; then
	echo "$PYTHONVER Running on Mac OSX Platform!"
	EXP="export VERSIONER_PYTHON_PREFER_32_BIT=yes"
	# Mountain Lion hack 
	if [ $DARWINVER == "12" ] || [ $DARWINVER == "13" ]; then
	    #echo " Using Lion (10.7) IOBluetooth Framework hack!"
	    echo " Using IOBluetooth-Compat Framework hack!"
	    DYLDMOD="export DYLD_FORCE_FLAT_NAMESPACE=1; export $DYLDPATH"
	else
	    DYLDMOD=
	fi
	ARCH="arch -i386"
else
	echo "$PYTHONVER Running on Default Platform!"
	DYLDMOD=
	EXP=
	ARCH=
fi
# Debugging Info
# echo "dirname:" `dirname $0`
# echo "basename:" `basename $0`
cd `dirname $0`
#echo $DYLDMOD; $EXP; $ARCH $PYTHON $GDBSERVER $*
$DYLDMOD; $EXP; $ARCH $PYTHON $GDBSERVER $*
