#!/bin/bash
OBJCOPY=arm-none-eabi-objcopy
STRIP=arm-none-eabi-strip

scriptdir=`dirname ${0}`
scriptdir=`(cd ${scriptdir}; pwd)`
scriptname=`basename ${0}`

set -e

function errorexit()
{
  errorcode=${1}
  shift
  echo $@
  exit ${errorcode}
}

function usage()
{
  echo "USAGE ${scriptname} <tostrip>"
}

tostripdir=`dirname "$1"`
tostripfile=`basename "$1"`


if [ -z ${tostripfile} ] ; then
  usage
  errorexit 0 "tostrip must be specified"
fi

cd "${tostripdir}"

#debugdir=.debug
#debugfile="${tostripfile}.debug"
debugfile="${tostripfile}.symbols"
#stripfile="${tostripfile}.stripped"
stripfile="${tostripfile}"

#if [ ! -d "${debugdir}" ] ; then
#  echo "creating dir ${tostripdir}/${debugdir}"
#  mkdir -p "${debugdir}"
#fi
echo "stripping ${tostripfile}, putting debug info into ${debugfile}"
#$OBJCOPY --only-keep-debug "${tostripfile}" "${debugdir}/${debugfile}"
#$STRIP --strip-debug --strip-unneeded "${tostripfile}"
#$OBJCOPY --add-gnu-debuglink="${debugdir}/${debugfile}" "${tostripfile}"
#chmod -x "${debugdir}/${debugfile}"

$OBJCOPY --only-keep-debug "${tostripfile}" "${debugfile}"
$STRIP --strip-debug --strip-unneeded "${tostripfile}" -o "${stripfile}"
$OBJCOPY --add-gnu-debuglink="${debugfile}" "${tostripfile}"
chmod -x "${debugfile}"

