#!/bin/sh
sudo codesign -f -s - /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app
codesign -vvv /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app
